import { ComponentFactoryResolver, OnInit, EventEmitter } from '@angular/core';
import { InputComponent } from '../inputComponent.component';
import { TextBoxComponent } from './textbox/textbox.component';
import { LabelComponent } from './label/label.component';
import { CheckBoxComponent } from './check-box/check-box.component';
import { TextAreaComponent } from './text-area/text-area.component';
import { SelectBoxComponent } from './select-box/select-box.component';
import { HiddenComponent } from './hidden/hidden.component';
import { FileUploadComponent } from './file-upload/file-upload.component';
import { ImageComponent } from './image/image.component';
import { AutoCompleteComponent } from './auto-complete/auto-complete.component';
import { ButtonComponent } from './button/button.component';
import { SwappingBoxComponent } from './swapping-box/swapping-box.component';
import { MapValueComponent } from './map-value/map-value.component';
import { RadioComponent } from './radio/radio.component';
import { DateComponent } from './date/date.component';
import { ButtonIconComponent } from './button-icon/button-icon.component';
import { AnimationService } from '../../service/animation.service';
import { ColorSelectComponent } from './color-select/color-select.component';
export declare class DynamicInputComponent implements OnInit {
    private componentFactoryResolver;
    private animationService;
    inputComp: InputComponent;
    data: Object;
    type: any;
    option: any;
    fieldCreation: any;
    inputIndex: any;
    rowIndex: any;
    callBack: EventEmitter<any>;
    panelCallBack: EventEmitter<any>;
    instantInput: InputComponent;
    componentTypes: {
        textBox: typeof TextBoxComponent;
        textArea: typeof TextAreaComponent;
        label: typeof LabelComponent;
        checkBox: typeof CheckBoxComponent;
        colorSelect: typeof ColorSelectComponent;
        selectBox: typeof SelectBoxComponent;
        hidden: typeof HiddenComponent;
        fileUpload: typeof FileUploadComponent;
        image: typeof ImageComponent;
        autoComplete: typeof AutoCompleteComponent;
        button: typeof ButtonComponent;
        buttonIcon: typeof ButtonIconComponent;
        swappingBox: typeof SwappingBoxComponent;
        mapValue: typeof MapValueComponent;
        radio: typeof RadioComponent;
        date: typeof DateComponent;
        number: typeof TextBoxComponent;
        password: typeof TextBoxComponent;
    };
    constructor(componentFactoryResolver: ComponentFactoryResolver, animationService: AnimationService);
    ngOnInit(): void;
    createComponent(): void;
    processCall(data: any): void;
}
//# sourceMappingURL=dynamic-input.component.d.ts.map